export const tracks = [
  {
    file: "YasMarina",
    id: "ae-2009",
    Location: "Yas Marina",
    Name: "Yas Marina Circuit",
    opened: 2009,
    firstgp: 2009,
    length: 5281,
    altitude: 9,
  },
  {
    file: "Spielberg",
    id: "at-1969",
    Location: "Spielberg",
    Name: "Red Bull Ring",
    opened: 1969,
    firstgp: 1970,
    length: 4318,
    altitude: 721,
  },
  {
    file: "Melbourne",
    id: "au-1953",
    Location: "Melbourne",
    Name: "Albert Park Circuit",
    opened: 1953,
    firstgp: 1996,
    length: 5278,
    altitude: 10,
  },
  {
    file: "Baku",
    id: "az-2016",
    Location: "Baku",
    Name: "Baku City Circuit",
    opened: 2016,
    firstgp: 2016,
    length: 6003,
    altitude: -25,
  },
  {
    file: "SpaFrancorchamps",
    id: "be-1925",
    Location: "Spa Francorchamps",
    Name: "Circuit de Spa-Francorchamps",
    opened: 1925,
    firstgp: 1950,
    length: 7004,
    altitude: 413,
  },
  {
    file: "Sakhir",
    id: "bh-2002",
    Location: "Sakhir",
    Name: "Bahrain International Circuit",
    opened: 2002,
    firstgp: 2004,
    length: 5412,
    altitude: -16,
  },
  {
    file: "SaoPaulo",
    id: "br-1940",
    Location: "Sao Paulo",
    Name: "Autódromo José Carlos Pace - Interlagos",
    opened: 1940,
    firstgp: 1973,
    length: 4309,
    altitude: 765,
  },
  {
    file: "Jacarepagua",
    id: "br-1977",
    Location: "Jacarepaguá",
    Name: "Autódromo Internacional Nelson Piquet",
    opened: 1977,
    firstgp: 1978,
    length: 5031,
    altitude: 3,
  },
  {
    file: "Montreal",
    id: "ca-1978",
    Location: "Montreal",
    Name: "Circuit Gilles-Villeneuve",
    opened: 1978,
    firstgp: 1978,
    length: 4361,
    altitude: 13,
  },
  {
    file: "Shanghai",
    id: "cn-2004",
    Location: "Shanghai",
    Name: "Shanghai International Circuit",
    opened: 2004,
    firstgp: 2004,
    length: 5451,
    altitude: 14,
  },
  {
    file: "Nurburg",
    id: "de-1927",
    Location: "Nürburg",
    Name: "Nürburgring",
    opened: 1927,
    firstgp: 1984,
    length: 5148,
    altitude: 627,
  },
  {
    file: "Hockenheim",
    id: "de-1932",
    Location: "Hockenheim",
    Name: "Hockenheimring",
    opened: 1932,
    firstgp: 1970,
    length: 4574,
    altitude: 148,
  },
  {
    file: "Barcelona",
    id: "es-1991",
    Location: "Barcelona",
    Name: "Circuit de Barcelona-Catalunya",
    opened: 1991,
    firstgp: 1991,
    length: 4655,
    altitude: 165,
  },
  {
    file: "MagnyCours",
    id: "fr-1960",
    Location: "Magny-Cours",
    Name: "Circuit de Nevers Magny-Cours",
    opened: 1960,
    firstgp: 1991,
    length: 4412,
    altitude: 230,
  },
  {
    file: "LeCastellet",
    id: "fr-1969",
    Location: "Le Castellet",
    Name: "Circuit Paul Ricard",
    opened: 1969,
    firstgp: 1971,
    length: 5842,
    altitude: 408,
  },
  {
    file: "Silverstone",
    id: "gb-1948",
    Location: "Silverstone",
    Name: "Silverstone Circuit",
    opened: 1948,
    firstgp: 1950,
    length: 5891,
    altitude: 196,
  },
  {
    file: "Budapest",
    id: "hu-1986",
    Location: "Budapest",
    Name: "Hungaroring",
    opened: 1986,
    firstgp: 1986,
    length: 4381,
    altitude: 239,
  },
  {
    file: "ScarperiaeSanPiero",
    id: "it-1914",
    Location: "Scarperia e San Piero",
    Name: "Autodromo Internazionale del Mugello",
    opened: 1914,
    firstgp: 2020,
    length: 5245,
    altitude: 292,
  },
  {
    file: "Monza",
    id: "it-1922",
    Location: "Monza",
    Name: "Autodromo Nazionale Monza",
    opened: 1922,
    firstgp: 1950,
    length: 5793,
    altitude: 142,
  },
  {
    file: "Imola",
    id: "it-1953",
    Location: "Imola",
    Name: "Autodromo Enzo e Dino Ferrari",
    opened: 1953,
    firstgp: 1980,
    length: 4909,
    altitude: 47,
  },
  {
    file: "Suzuka",
    id: "jp-1962",
    Location: "Suzuka",
    Name: "Suzuka International Racing Course",
    opened: 1962,
    firstgp: 1987,
    length: 5807,
    altitude: 60,
  },
  {
    file: "Monaco",
    id: "mc-1929",
    Location: "Monaco",
    Name: "Circuit de Monaco",
    opened: 1929,
    firstgp: 1929,
    length: 3337,
    altitude: 47,
  },
  {
    file: "MexicoCity",
    id: "mx-1962",
    Location: "Mexico City",
    Name: "Autódromo Hermanos Rodríguez",
    opened: 1962,
    firstgp: 1963,
    length: 4304,
    altitude: 2232,
  },
  {
    file: "Sepang",
    id: "my-1999",
    Location: "Sepang",
    Name: "Sepang International Circuit",
    opened: 1999,
    firstgp: 1999,
    length: 5543,
    altitude: 39,
  },
  {
    file: "Zandvoort",
    id: "nl-1948",
    Location: "Zandvoort",
    Name: "Circuit Zandvoort",
    opened: 1948,
    firstgp: 1952,
    length: 4259,
    altitude: 3,
  },
  {
    file: "Estoril",
    id: "pt-1972",
    Location: "Estoril",
    Name: "Autódromo do Estoril",
    opened: 1972,
    firstgp: 1984,
    length: 4349,
    altitude: 80,
  },
  {
    file: "Portimao",
    id: "pt-2008",
    Location: "Portimão",
    Name: "Autódromo Internacional do Algarve",
    opened: 2008,
    firstgp: 2020,
    length: 4653,
    altitude: 44,
  },
  {
    file: "Lusail",
    id: "qa-2004",
    Location: "Lusail",
    Name: "Losail International Circuit",
    opened: 2004,
    firstgp: 2021,
    length: 5380,
    altitude: 5,
  },
  {
    file: "Sochi",
    id: "ru-2014",
    Location: "Sochi",
    Name: "Sochi Autodrom",
    opened: 2014,
    firstgp: 2014,
    length: 5848,
    altitude: 23,
  },
  {
    file: "Jeddah",
    id: "sa-2021",
    Location: "Jeddah",
    Name: "Jeddah Corniche Circuit",
    opened: 2021,
    firstgp: 2021,
    length: 6175,
    altitude: 12,
  },
  {
    file: "Singapore",
    id: "sg-2008",
    Location: "Singapore",
    Name: "Marina Bay Street Circuit",
    opened: 2008,
    firstgp: 2008,
    length: 4928,
    altitude: 18,
  },
  {
    file: "Istanbul",
    id: "tr-2005",
    Location: "Istanbul",
    Name: "Intercity Istanbul Park",
    opened: 2005,
    firstgp: 2005,
    length: 5338,
    altitude: 150,
  },
  {
    file: "Austin",
    id: "us-2012",
    Location: "Austin",
    Name: "Circuit of the Americas",
    opened: 2012,
    firstgp: 2012,
    length: 5514,
    altitude: 130,
  },
  {
    file: "Miami",
    id: "us-2022",
    Location: "Miami",
    Name: "Miami International Autodrome",
    opened: 2022,
    firstgp: 2022,
    length: 5412,
    altitude: 1,
  },
  {
    file: "LasVegas",
    id: "us-2023",
    Location: "Las Vegas",
    Name: "Las Vegas Street Circuit",
    opened: 2023,
    firstgp: 2023,
    length: 6116,
    altitude: 610,
  },
];
